version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: and
        validate:       
          - do: approvals
            min:
              count: 1
            block:
              changes_requested: true
            limit:
              users: ['rsiennapt']
          - do: approvals
            min:
              count: 1
            block:
              changes_requested: true
            limit:
              users: ['davidfoliveira']
